var searchData=
[
  ['s_20padding_20length_20in_20bytes_0',['SodiumHandler&apos;s Padding Length in Bytes',['../class_config_1_1_encryption.html#autotoc_md77',1,'']]],
  ['samesite_1',['SameSite',['../class_config_1_1_cookie.html#autotoc_md67',1,'Cookie SameSite'],['../class_config_1_1_security.html#autotoc_md151',1,'CSRF SameSite'],['../deprecated.html#_deprecated000006',1,'CSRF SameSite']]],
  ['save_20path_2',['Session Save Path',['../class_config_1_1_session.html#autotoc_md159',1,'']]],
  ['secure_3',['Cookie Secure',['../class_config_1_1_cookie.html#autotoc_md63',1,'']]],
  ['secure_20requests_4',['Force Global Secure Requests',['../class_config_1_1_app.html#autotoc_md17',1,'']]],
  ['security_5',['Security',['../class_config_1_1_security.html',1,'Config']]],
  ['security_20policy_6',['Content Security Policy',['../class_config_1_1_app.html#autotoc_md21',1,'']]],
  ['services_7',['Services',['../class_config_1_1_services.html',1,'Config']]],
  ['session_8',['Session',['../class_app_1_1_filters_1_1_session.html',1,'Session'],['../class_config_1_1_session.html',1,'Session']]],
  ['session_20cookie_20name_9',['Session Cookie Name',['../class_config_1_1_session.html#autotoc_md155',1,'']]],
  ['session_20database_20group_10',['Session Database Group',['../class_config_1_1_session.html#autotoc_md167',1,'']]],
  ['session_20driver_11',['Session Driver',['../C:/xampp/htdocs/liquidador/app/Config/Session.php#autotoc_md153',1,'']]],
  ['session_20expiration_12',['Session Expiration',['../class_config_1_1_session.html#autotoc_md157',1,'']]],
  ['session_20match_20ip_13',['Session Match IP',['../class_config_1_1_session.html#autotoc_md161',1,'']]],
  ['session_20regenerate_20destroy_14',['Session Regenerate Destroy',['../class_config_1_1_session.html#autotoc_md165',1,'']]],
  ['session_20save_20path_15',['Session Save Path',['../class_config_1_1_session.html#autotoc_md159',1,'']]],
  ['session_20time_20to_20update_16',['Session Time to Update',['../class_config_1_1_session.html#autotoc_md163',1,'']]],
  ['sessionadmin_17',['SessionAdmin',['../class_app_1_1_filters_1_1_session_admin.html',1,'App::Filters']]],
  ['set_18',['Default Character Set',['../class_config_1_1_app.html#autotoc_md15',1,'']]],
  ['settings_19',['settings',['../C:/xampp/htdocs/liquidador/app/Config/Cache.php#autotoc_md47',1,'File settings'],['../C:/xampp/htdocs/liquidador/app/Config/Cache.php#autotoc_md49',1,'Memcached settings'],['../C:/xampp/htdocs/liquidador/app/Config/Cache.php#autotoc_md51',1,'Redis settings']]],
  ['share_20options_20',['CURLRequest Share Options',['../class_config_1_1_c_u_r_l_request.html#autotoc_md71',1,'']]],
  ['site_20url_21',['Base Site URL',['../class_config_1_1_app.html#autotoc_md1',1,'']]],
  ['sodiumhandler_20s_20padding_20length_20in_20bytes_22',['SodiumHandler&apos;s Padding Length in Bytes',['../class_config_1_1_encryption.html#autotoc_md77',1,'']]],
  ['starter_23',['Encryption Key Starter',['../class_config_1_1_encryption.html#autotoc_md73',1,'']]],
  ['status_20codes_24',['DO NOT LOG STATUS CODES',['../C:/xampp/htdocs/liquidador/app/Config/Exceptions.php#autotoc_md83',1,'']]],
  ['string_25',['Cache Include Query String',['../C:/xampp/htdocs/liquidador/app/Config/Cache.php#autotoc_md39',1,'']]],
  ['supported_20locales_26',['Supported Locales',['../C:/xampp/htdocs/liquidador/app/Config/App.php#autotoc_md11',1,'']]],
  ['system_20folder_20name_27',['SYSTEM FOLDER NAME',['../class_config_1_1_paths.html#autotoc_md125',1,'']]]
];
