var searchData=
[
  ['cache_0',['Cache',['../class_config_1_1_cache.html',1,'Config']]],
  ['cache_20directory_20path_1',['Cache Directory Path',['../class_config_1_1_cache.html#autotoc_md37',1,'Cache Directory Path'],['../deprecated.html#_deprecated000001',1,'Cache Directory Path']]],
  ['cache_20handlers_2',['Available Cache Handlers',['../C:/xampp/htdocs/liquidador/app/Config/Cache.php#autotoc_md53',1,'']]],
  ['cache_20include_20query_20string_3',['Cache Include Query String',['../C:/xampp/htdocs/liquidador/app/Config/Cache.php#autotoc_md39',1,'']]],
  ['cerrarsesion_4',['cerrarSesion',['../class_app_1_1_controllers_1_1_usuarios_controller.html#a0f7728fa1e22b7b7a8281aebd5c5e50f',1,'App::Controllers::UsuariosController']]],
  ['character_20set_5',['Default Character Set',['../class_config_1_1_app.html#autotoc_md15',1,'']]],
  ['characters_6',['Reserved Characters',['../class_config_1_1_cache.html#autotoc_md45',1,'']]],
  ['class_20map_7',['Class Map',['../C:/xampp/htdocs/liquidador/app/Config/Autoload.php#autotoc_md27',1,'']]],
  ['codes_8',['DO NOT LOG STATUS CODES',['../C:/xampp/htdocs/liquidador/app/Config/Exceptions.php#autotoc_md83',1,'']]],
  ['collect_20var_20data_9',['Collect Var Data',['../class_config_1_1_toolbar.html#autotoc_md173',1,'']]],
  ['collectors_10',['Toolbar Collectors',['../C:/xampp/htdocs/liquidador/app/Config/Toolbar.php#autotoc_md171',1,'']]],
  ['commands_20views_11',['Generator Commands&apos; Views',['../C:/xampp/htdocs/liquidador/app/Config/Generators.php#autotoc_md99',1,'']]],
  ['composer_20packages_12',['Enable Auto-Discovery Within Composer Packages?',['../C:/xampp/htdocs/liquidador/app/Config/Modules.php#autotoc_md117',1,'']]],
  ['config_13',['Config',['../namespace_config.html',1,'']]],
  ['configuration_14',['AUTOLOADER CONFIGURATION',['../class_config_1_1_autoload.html#autotoc_md23',1,'']]],
  ['content_20security_20policy_15',['Content Security Policy',['../class_config_1_1_app.html#autotoc_md21',1,'']]],
  ['contentsecuritypolicy_16',['ContentSecurityPolicy',['../class_config_1_1_content_security_policy.html',1,'Config']]],
  ['cookie_17',['Cookie',['../class_config_1_1_cookie.html',1,'Config']]],
  ['cookie_20domain_18',['Cookie Domain',['../class_config_1_1_cookie.html#autotoc_md61',1,'']]],
  ['cookie_20expires_20timestamp_19',['Cookie Expires Timestamp',['../C:/xampp/htdocs/liquidador/app/Config/Cookie.php#autotoc_md57',1,'']]],
  ['cookie_20httponly_20',['Cookie HTTPOnly',['../class_config_1_1_cookie.html#autotoc_md65',1,'']]],
  ['cookie_20name_21',['Cookie Name',['../class_config_1_1_security.html#autotoc_md143',1,'CSRF Cookie Name'],['../class_config_1_1_session.html#autotoc_md155',1,'Session Cookie Name']]],
  ['cookie_20path_22',['Cookie Path',['../class_config_1_1_cookie.html#autotoc_md59',1,'']]],
  ['cookie_20prefix_23',['Cookie Prefix',['../class_config_1_1_cookie.html#autotoc_md55',1,'']]],
  ['cookie_20raw_24',['Cookie Raw',['../class_config_1_1_cookie.html#autotoc_md69',1,'']]],
  ['cookie_20samesite_25',['Cookie SameSite',['../class_config_1_1_cookie.html#autotoc_md67',1,'']]],
  ['cookie_20secure_26',['Cookie Secure',['../class_config_1_1_cookie.html#autotoc_md63',1,'']]],
  ['crearnuevodtf_27',['crearNuevoDtf',['../class_app_1_1_controllers_1_1_admin_1_1_admin_controller.html#a2d9f5935d1df3f9cd5fd9a5287434a4a',1,'App::Controllers::Admin::AdminController']]],
  ['crearnuevoipc_28',['crearNuevoIpc',['../class_app_1_1_controllers_1_1_admin_1_1_admin_controller.html#ae15bd01203ee17ee8c5f6e769fd9c289',1,'App::Controllers::Admin::AdminController']]],
  ['csrf_20cookie_20name_29',['CSRF Cookie Name',['../class_config_1_1_security.html#autotoc_md143',1,'']]],
  ['csrf_20expires_30',['CSRF Expires',['../class_config_1_1_security.html#autotoc_md145',1,'']]],
  ['csrf_20header_20name_31',['CSRF Header Name',['../class_config_1_1_security.html#autotoc_md141',1,'']]],
  ['csrf_20protection_20method_32',['CSRF Protection Method',['../C:/xampp/htdocs/liquidador/app/Config/Security.php#autotoc_md135',1,'']]],
  ['csrf_20redirect_33',['CSRF Redirect',['../class_config_1_1_security.html#autotoc_md149',1,'']]],
  ['csrf_20regenerate_34',['CSRF Regenerate',['../class_config_1_1_security.html#autotoc_md147',1,'']]],
  ['csrf_20samesite_35',['CSRF SameSite',['../class_config_1_1_security.html#autotoc_md151',1,'CSRF SameSite'],['../deprecated.html#_deprecated000006',1,'CSRF SameSite']]],
  ['csrf_20token_20name_36',['CSRF Token Name',['../class_config_1_1_security.html#autotoc_md139',1,'']]],
  ['csrf_20token_20randomization_37',['CSRF Token Randomization',['../class_config_1_1_security.html#autotoc_md137',1,'']]],
  ['curlrequest_38',['CURLRequest',['../class_config_1_1_c_u_r_l_request.html',1,'Config']]],
  ['curlrequest_20share_20options_39',['CURLRequest Share Options',['../class_config_1_1_c_u_r_l_request.html#autotoc_md71',1,'']]]
];
