var searchData=
[
  ['data_0',['Collect Var Data',['../class_config_1_1_toolbar.html#autotoc_md173',1,'']]],
  ['database_1',['Database',['../class_config_1_1_database.html',1,'Config']]],
  ['database_20group_2',['Session Database Group',['../class_config_1_1_session.html#autotoc_md167',1,'']]],
  ['date_20format_20for_20logs_3',['Date Format for Logs',['../class_config_1_1_logger.html#autotoc_md105',1,'']]],
  ['de_20obsoletos_4',['Lista de obsoletos',['../deprecated.html',1,'']]],
  ['debug_20toolbar_5',['Debug Toolbar',['../class_config_1_1_toolbar.html#autotoc_md169',1,'']]],
  ['debug_20trace_6',['HIDE FROM DEBUG TRACE',['../C:/xampp/htdocs/liquidador/app/Config/Exceptions.php#autotoc_md87',1,'']]],
  ['default_20character_20set_7',['Default Character Set',['../class_config_1_1_app.html#autotoc_md15',1,'']]],
  ['default_20locale_8',['Default Locale',['../class_config_1_1_app.html#autotoc_md7',1,'']]],
  ['default_20ttl_9',['Default TTL',['../class_config_1_1_cache.html#autotoc_md43',1,'']]],
  ['demandantemodel_10',['DemandanteModel',['../class_app_1_1_models_1_1_demandante_model.html',1,'App::Models']]],
  ['deprecations_11',['LOG LEVEL THRESHOLD FOR DEPRECATIONS',['../class_config_1_1_exceptions.html#autotoc_md91',1,'']]],
  ['deprecations_20instead_20of_20throwing_12',['LOG DEPRECATIONS INSTEAD OF THROWING?',['../class_config_1_1_exceptions.html#autotoc_md89',1,'']]],
  ['destroy_13',['Session Regenerate Destroy',['../class_config_1_1_session.html#autotoc_md165',1,'']]],
  ['digest_14',['Encryption digest',['../class_config_1_1_encryption.html#autotoc_md79',1,'']]],
  ['directories_15',['Watched Directories',['../C:/xampp/htdocs/liquidador/app/Config/Toolbar.php#autotoc_md181',1,'']]],
  ['directory_20name_16',['DIRECTORY NAME',['../class_config_1_1_paths.html#autotoc_md131',1,'TESTS DIRECTORY NAME'],['../class_config_1_1_paths.html#autotoc_md133',1,'VIEW DIRECTORY NAME'],['../class_config_1_1_paths.html#autotoc_md129',1,'WRITABLE DIRECTORY NAME']]],
  ['directory_20path_17',['Directory Path',['../class_config_1_1_cache.html#autotoc_md37',1,'Cache Directory Path'],['../deprecated.html#_deprecated000001',1,'Cache Directory Path']]],
  ['disable_20migrations_18',['Enable/Disable Migrations',['../class_config_1_1_migrations.html#autotoc_md109',1,'']]],
  ['discovery_19',['Enable Auto-Discovery?',['../C:/xampp/htdocs/liquidador/app/Config/Modules.php#autotoc_md115',1,'']]],
  ['discovery_20rules_20',['Auto-Discovery Rules',['../C:/xampp/htdocs/liquidador/app/Config/Modules.php#autotoc_md119',1,'']]],
  ['discovery_20within_20composer_20packages_21',['Enable Auto-Discovery Within Composer Packages?',['../C:/xampp/htdocs/liquidador/app/Config/Modules.php#autotoc_md117',1,'']]],
  ['do_20not_20log_20status_20codes_22',['DO NOT LOG STATUS CODES',['../C:/xampp/htdocs/liquidador/app/Config/Exceptions.php#autotoc_md83',1,'']]],
  ['doctypes_23',['DocTypes',['../class_config_1_1_doc_types.html',1,'Config']]],
  ['domain_24',['Cookie Domain',['../class_config_1_1_cookie.html#autotoc_md61',1,'']]],
  ['driver_25',['Session Driver',['../C:/xampp/htdocs/liquidador/app/Config/Session.php#autotoc_md153',1,'']]],
  ['driver_20to_20use_26',['Encryption Driver to Use',['../class_config_1_1_encryption.html#autotoc_md75',1,'']]],
  ['dtfmodel_27',['DtfModel',['../class_app_1_1_models_1_1_dtf_model.html',1,'App::Models']]]
];
